# Generated by Django 2.1.5 on 2019-01-21 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190109_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='main.Product'),
        ),
    ]
