# Generated by Django 2.1.5 on 2019-01-30 18:55

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_buyeraddress_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIssue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('issue', models.TextField(max_length=1000)),
                ('created', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'User Issue',
                'verbose_name_plural': 'User Issues',
            },
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='cost',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='KES', max_digits=14),
        ),
    ]
