# Generated by Django 2.1.5 on 2019-02-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20190130_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant_info',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, max_length=1500, null=True),
        ),
    ]
